apiVersion: v1
kind: Service
metadata:
  name:
  labels:
    app:
spec:
  selector:
    app:
  ports:
    - protocol: TCP
      name: grpc
      port: 31000
      targetPort: 31000
    - protocol: TCP
      name: prometheus
      port: 9090
      targetPort: 9090
  type: ClusterIP